/** @type {import('next').NextConfig} */
const nextConfig = {
  // Old standalone routes that used to be live and were likely crawled/indexed by Google before
  // being consolidated into other pages. 301s (statusCode: 301, not the default 308 `permanent`)
  // so any existing backlinks/search index entries carry over instead of 404ing.
  async redirects() {
    return [
      { source: '/whatsapp/ai-agent', destination: '/whatsapp#ai-agent', statusCode: 301 },
      { source: '/whatsapp/analytics', destination: '/whatsapp#analytics', statusCode: 301 },
      { source: '/whatsapp/automation', destination: '/whatsapp#automation', statusCode: 301 },
      { source: '/whatsapp/broadcast', destination: '/whatsapp#broadcast', statusCode: 301 },
      { source: '/whatsapp/numbers', destination: '/whatsapp#multiple-numbers', statusCode: 301 },
      { source: '/whatsapp/shared-inbox', destination: '/whatsapp#team-inbox', statusCode: 301 },
      { source: '/pricing-new', destination: '/pricing', statusCode: 301 },
      // Never a route in this codebase's history — an old marketing/backlink URL Google has
      // indexed from elsewhere. Closest current page by intent.
      { source: '/whatsapp-crm', destination: '/whatsapp', statusCode: 301 },

      // Below: bulk 301s generated from a Google Analytics "404 pages" export — almost entirely
      // old "AiTrillion" content (this site's previous product/brand: Shopify loyalty, email/SMS
      // marketing, web push) plus a handful of pre-restructure AiEngage CRM URLs. Prefix rules
      // (`/:path*`) cover whole legacy sections with no current equivalent — safe because none of
      // these prefixes are used by any live route today. `/blog/*` is deliberately NOT a prefix
      // rule (unlike the others) since /blog/[slug] is a real, live, CMS-backed route — every old
      // blog slug below is an exact match instead, so a real current post is never shadowed.
      // Two rows from the source export were skipped as not real paths: `/wp-*.php` (generic
      // WordPress bot-scan pattern, not a specific URL) and a bare `/*` (GA's own "everything
      // else" aggregation marker — redirecting it would send the whole site to the homepage).
      { source: '/best-shopify-apps/:path*', destination: '/', statusCode: 301 },
      { source: '/brands-profiling/:path*', destination: '/', statusCode: 301 },
      { source: '/case-study/:path*', destination: '/', statusCode: 301 },
      { source: '/category/:path*', destination: '/', statusCode: 301 },
      { source: '/features/:path*', destination: '/', statusCode: 301 },
      { source: '/review/:path*', destination: '/', statusCode: 301 },
      { source: '/tag/:path*', destination: '/', statusCode: 301 },
      { source: '/uncategorized/:path*', destination: '/', statusCode: 301 },
      { source: '/whats-new-on-aitrillion/:path*', destination: '/', statusCode: 301 },
      { source: '/wp-content/:path*', destination: '/', statusCode: 301 },
      { source: '/about-us', destination: '/about', statusCode: 301 },
      { source: '/about-us-aiengage', destination: '/about', statusCode: 301 },
      // Sourced without the trailing slash: Next's own trailing-slash normalization (308) strips
      // it before custom redirects are evaluated, so a source ending in `/` never actually matches.
      { source: '/ai-prediction', destination: '/', statusCode: 301 },
      { source: '/ai-predictions', destination: '/ai', statusCode: 301 },
      { source: '/aiengage-crm', destination: '/', statusCode: 301 },
      { source: '/aiengage-crm/about-us-aiengage', destination: '/about', statusCode: 301 },
      { source: '/aiengage-crm/aiengage-vs-keap', destination: '/keap-alternative', statusCode: 301 },
      { source: '/aiengage-crm/aiengage-vs-zoho', destination: '/zoho-alternative', statusCode: 301 },
      { source: '/aiengage-crm/audience-segmentation', destination: '/marketing-campaigns', statusCode: 301 },
      { source: '/aiengage-crm/automation-tools', destination: '/automation', statusCode: 301 },
      { source: '/aiengage-crm/book-a-demo', destination: '/book-a-demo', statusCode: 301 },
      { source: '/aiengage-crm/campaign-analytics', destination: '/marketing-campaigns#campaign-insights', statusCode: 301 },
      { source: '/aiengage-crm/customer-insights-dashboard', destination: '/customer-management', statusCode: 301 },
      { source: '/aiengage-crm/lead-management', destination: '/lead-management', statusCode: 301 },
      { source: '/aiengage-crm/pricing', destination: '/pricing', statusCode: 301 },
      { source: '/aiengage-crm/sales-pipeline-management', destination: '/sales-pipeline', statusCode: 301 },
      { source: '/aiengage-vs-keap', destination: '/keap-alternative', statusCode: 301 },
      { source: '/aiengage-vs-zoho', destination: '/zoho-alternative', statusCode: 301 },
      { source: '/aitrillion-demo-email', destination: '/', statusCode: 301 },
      { source: '/aitrillion-for-store-owners', destination: '/', statusCode: 301 },
      { source: '/bangalore-shopify-meetup', destination: '/', statusCode: 301 },
      { source: '/bfcm-hub', destination: '/', statusCode: 301 },
      { source: '/blog/10-key-facts-to-get-started-with-shopify-email-marketing', destination: '/', statusCode: 301 },
      { source: '/blog/10-proven-strategies-to-grow-your-email-sms-list-on-shopify', destination: '/', statusCode: 301 },
      { source: '/blog/10-sales-and-marketing-strategies-for-shopify-stores', destination: '/', statusCode: 301 },
      { source: '/blog/10-ways-to-boost-your-sales-with-ecommerce-affiliate-marketing', destination: '/', statusCode: 301 },
      { source: '/blog/6-shopify-personalization-strategies-that-will-elevate-your-retention-rate', destination: '/', statusCode: 301 },
      { source: '/blog/9-email-marketing-automation-to-increase-sales-in-an-ecommerce-store', destination: '/', statusCode: 301 },
      { source: '/blog/abandoned-cart-email-templates-fashion-ecommerce', destination: '/', statusCode: 301 },
      { source: '/blog/affiliate-marketing-for-ecommerce-boosting-sales-and-engagement', destination: '/', statusCode: 301 },
      { source: '/blog/affiliate-vs-influencer-marketing-for-ecommerce', destination: '/', statusCode: 301 },
      { source: '/blog/ai-for-shopify-theme-customization', destination: '/', statusCode: 301 },
      { source: '/blog/ai-product-recommendations-shopify', destination: '/', statusCode: 301 },
      { source: '/blog/ai-smart-automation-for-beauty-cosmetic-shopify-brands', destination: '/', statusCode: 301 },
      { source: '/blog/aitrillion-and-ecpower-a-powerful-integration-for-enhanced-customer-engagement', destination: '/', statusCode: 301 },
      { source: '/blog/aitrillion-the-best-alternative-of-pushowl', destination: '/', statusCode: 301 },
      { source: '/blog/aitrillion-vs-loyaltylion', destination: '/', statusCode: 301 },
      { source: '/blog/aitrillion-vs-mailchimp', destination: '/', statusCode: 301 },
      { source: '/blog/aitrillion-vs-smile-io', destination: '/', statusCode: 301 },
      { source: '/blog/b2b-email-marketing-best-practices', destination: '/', statusCode: 301 },
      { source: '/blog/benefits-of-loyalty-programs-shopify', destination: '/', statusCode: 301 },
      { source: '/blog/best-affiliate-marketing-apps-shopify-2025', destination: '/', statusCode: 301 },
      { source: '/blog/best-email-marketing-apps-for-shopify-top-11-picks-for-2025', destination: '/', statusCode: 301 },
      { source: '/blog/best-loyalty-rewards-apps-for-shopify-top-5-picks-for-2025', destination: '/', statusCode: 301 },
      { source: '/blog/best-loyalty-rewards-apps-for-shopify-top-5-picks-for-2026', destination: '/', statusCode: 301 },
      { source: '/blog/best-places-product-recommendations-shopify', destination: '/', statusCode: 301 },
      { source: '/blog/best-product-recommendation-apps-for-shopify', destination: '/', statusCode: 301 },
      { source: '/blog/best-product-review-apps-for-shopify', destination: '/', statusCode: 301 },
      { source: '/blog/best-shopify-agencies-in-australia', destination: '/', statusCode: 301 },
      { source: '/blog/best-shopify-apps-to-increase-sales', destination: '/', statusCode: 301 },
      { source: '/blog/best-shopify-dropshipping-apps', destination: '/', statusCode: 301 },
      { source: '/blog/best-shopify-marketing-apps', destination: '/', statusCode: 301 },
      { source: '/blog/best-shopify-popup-apps', destination: '/', statusCode: 301 },
      { source: '/blog/best-shopify-recurring-membership-apps', destination: '/', statusCode: 301 },
      { source: '/blog/best-shopify-upsell-apps', destination: '/', statusCode: 301 },
      { source: '/blog/best-shopify-whatsapp-marketing-apps', destination: '/', statusCode: 301 },
      { source: '/blog/best-shopify-workflow-automation-apps', destination: '/', statusCode: 301 },
      { source: '/blog/best-smile-io-alternative-shopify-loyalty-rewards-program', destination: '/', statusCode: 301 },
      { source: '/blog/bfcm-2019-boost-your-audience-sales-in-the-next-3-months', destination: '/', statusCode: 301 },
      { source: '/blog/bfcm-boost-your-audience-sales-in-the-next-3-months', destination: '/', statusCode: 301 },
      { source: '/blog/bfcm-proven-strategies-for-shopify', destination: '/', statusCode: 301 },
      { source: '/blog/boost-your-shopify-product-reviews-with-aitrillions-integrated-platform', destination: '/', statusCode: 301 },
      { source: '/blog/choose-best-loyalty-program-for-retail-business', destination: '/', statusCode: 301 },
      { source: '/blog/christmas-email-subject-lines-for-shopify', destination: '/', statusCode: 301 },
      { source: '/blog/complete-guide-to-web-push-notifications', destination: '/', statusCode: 301 },
      { source: '/blog/create-an-integrated-customer-journey-with-aitrillion', destination: '/', statusCode: 301 },
      { source: '/blog/elevate-your-subscription-with-aitrillion-and-recurpay-integration', destination: '/', statusCode: 301 },
      { source: '/blog/email-automation-with-aitrillion', destination: '/', statusCode: 301 },
      { source: '/blog/engage-with-customers-at-different-customer-lifecycle-stages', destination: '/', statusCode: 301 },
      { source: '/blog/experience-marketing-automation-powered-with-actionable-artificial-intelligence-get-aitrillion', destination: '/', statusCode: 301 },
      { source: '/blog/fix-cart-abandonment-boost-sales', destination: '/', statusCode: 301 },
      { source: '/blog/get-artificial-intelligence-and-upshot-your-abandoned-cart-recovery-performances', destination: '/', statusCode: 301 },
      { source: '/blog/get-more-reviews-from-your-customers-with-aitrillion', destination: '/', statusCode: 301 },
      { source: '/blog/global-ecommerce-at-a-crossroads-navigating-trumps-tariff-shock', destination: '/', statusCode: 301 },
      { source: '/blog/grow-your-revenue-by-segmenting-your-customers', destination: '/', statusCode: 301 },
      { source: '/blog/growave-alternatives', destination: '/', statusCode: 301 },
      { source: '/blog/guide-to-more-repeat-purchases-with-aitrillion-loyalty-program', destination: '/', statusCode: 301 },
      { source: '/blog/guide-to-product-review-syndication', destination: '/', statusCode: 301 },
      { source: '/blog/guide-to-reinventing-loyalty-programs', destination: '/', statusCode: 301 },
      { source: '/blog/guide-to-shopify-web-push-notification', destination: '/', statusCode: 301 },
      { source: '/blog/guide-to-web-push-notification', destination: '/', statusCode: 301 },
      { source: '/blog/how-customer-loyalty-influences-customer-retention', destination: '/', statusCode: 301 },
      { source: '/blog/how-multi-channel-marketing-platform-on-shopify-boosts-customer-retention', destination: '/', statusCode: 301 },
      { source: '/blog/how-to-build-email-list-for-shopify', destination: '/', statusCode: 301 },
      { source: '/blog/how-to-fix-low-email-open-rates', destination: '/', statusCode: 301 },
      { source: '/blog/how-to-get-your-customers-to-spend-more-using-aitrillion-loyalty-program', destination: '/', statusCode: 301 },
      { source: '/blog/how-to-set-up-and-manage-a-shopify-affiliate-marketing-program', destination: '/', statusCode: 301 },
      { source: '/blog/how-to-use-affiliate-marketing-to-grow-your-business', destination: '/', statusCode: 301 },
      { source: '/blog/improve-your-ecommerce-site-performance-speed-to-boost-conversions', destination: '/', statusCode: 301 },
      { source: '/blog/increase-repeat-sales-shopify-whatsapp-marketing', destination: '/', statusCode: 301 },
      { source: '/blog/klaviyo-alternatives', destination: '/', statusCode: 301 },
      { source: '/blog/loyalty-point-emails', destination: '/', statusCode: 301 },
      { source: '/blog/loyalty-program-examples-for-fashion-and-apparel-brands', destination: '/', statusCode: 301 },
      { source: '/blog/loyaltylion-alternatives', destination: '/', statusCode: 301 },
      { source: '/blog/marsello-alternatives', destination: '/', statusCode: 301 },
      { source: '/blog/migrate-from-klaviyo-best-alternative-for-shopify-email-sms-marketing', destination: '/', statusCode: 301 },
      { source: '/blog/new-year-email-examples-for-shopify-store', destination: '/', statusCode: 301 },
      { source: '/blog/oberlo-shutdown-switch-to-aitrillion', destination: '/', statusCode: 301 },
      { source: '/blog/personalized-shopping-experience-fashion-ecommerce', destination: '/', statusCode: 301 },
      { source: '/blog/power-up-your-store-with-aitrillions-membership-program', destination: '/', statusCode: 301 },
      { source: '/blog/product-recommendation-how-it-can-make-your-customers-feel-valued', destination: '/', statusCode: 301 },
      { source: '/blog/quick-bfcm-tips-for-ecommerce-sellers', destination: '/', statusCode: 301 },
      { source: '/blog/ready-for-the-rush-get-your-store-bfcm-ready-with-aitrillion', destination: '/', statusCode: 301 },
      { source: '/blog/sendinblue-alternatives', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-email-campaigns-best-practices', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-email-marketing-cost-pricing-guide', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-email-vs-whatsapp-marketing', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-loyalty-program-mistakes-to-avoid', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-marketing-strategies-fashion-and-clothing-brands', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-membership-program-how-it-works', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-post-purchase-email-examples', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-product-tagging', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-subscription-apps', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-unite-2021-online-store-2-0-and-themes-faqs', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-web-push-notification-how-to-increase-your-store-sales', destination: '/', statusCode: 301 },
      { source: '/blog/shopify-whatsapp-marketing-automation', destination: '/', statusCode: 301 },
      { source: '/blog/smile-io-alternatives', destination: '/', statusCode: 301 },
      { source: '/blog/the-complete-guide-to-reinventing-loyalty-programs-examples-and-templates-included', destination: '/', statusCode: 301 },
      { source: '/blog/the-importance-of-social-media-for-an-ecommerce-store-owner', destination: '/', statusCode: 301 },
      { source: '/blog/this-bfcm-shift-your-focus-to-loyalty-rewards-program', destination: '/', statusCode: 301 },
      { source: '/blog/tips-to-increase-your-store-sales-using-emails-bfcm', destination: '/', statusCode: 301 },
      { source: '/blog/tips-to-reduce-bounce-rate-and-boost-your-conversions', destination: '/', statusCode: 301 },
      { source: '/blog/tips-to-stop-your-emails-from-going-to-spam', destination: '/', statusCode: 301 },
      { source: '/blog/tips-to-win-back-lapsed-customers', destination: '/', statusCode: 301 },
      { source: '/blog/top-10-yotpo-alternatives-for-shopify-email-sms-marketing', destination: '/', statusCode: 301 },
      { source: '/blog/top-shopify-agencies-in-usa', destination: '/', statusCode: 301 },
      { source: '/blog/unlock-your-shopify-stores-growth-potential-with-aitrillions-marketing-automation-a-comprehensive-guide-to-boost-your-sales-and-save-time', destination: '/', statusCode: 301 },
      { source: '/blog/upsell-vs-cross-sell-difference-and-importance-in-shopify-store', destination: '/', statusCode: 301 },
      { source: '/blog/use-ai-product-recommendations-to-increase-aov', destination: '/', statusCode: 301 },
      { source: '/blog/use-web-push-notifications-to-boost-customer-engagement', destination: '/', statusCode: 301 },
      { source: '/blog/using-abandoned-cart-emails-to-recover-lost-sales-on-shopify', destination: '/', statusCode: 301 },
      { source: '/blog/using-customer-data-to-optimize-your-shopify-loyalty-program', destination: '/', statusCode: 301 },
      { source: '/blog/vibrant-smart-popups-drive-away-your-stubby-sales-blues', destination: '/', statusCode: 301 },
      { source: '/blog/virtual-shopify-meetup-recap-recurring-revenue-strategise-with-aitrillion-founders', destination: '/', statusCode: 301 },
      { source: '/blog/wati-aitrillion-integration-automate-whatsapp-messaging-with-workflow-automation', destination: '/', statusCode: 301 },
      { source: '/blog/what-is-ecommerce-automation-how-it-works', destination: '/', statusCode: 301 },
      { source: '/blog/what-is-ecommerce-workflow-automation', destination: '/', statusCode: 301 },
      { source: '/blog/what-is-ecommerce-workflow-automation-easy-steps-to-design-workflow-automation-for-your-marketing', destination: '/', statusCode: 301 },
      { source: '/blog/whatsapp-marketing-automation-fmcg-brands', destination: '/', statusCode: 301 },
      { source: '/blog/whatsapp-marketing-for-beauty-brands', destination: '/', statusCode: 301 },
      { source: '/blog/work-smart-automate-your-marketing-today', destination: '/', statusCode: 301 },
      { source: '/blog/yotpo-alternatives', destination: '/', statusCode: 301 },
      { source: '/commercial-sales-manager', destination: '/', statusCode: 301 },
      { source: '/complete-guide-to-get-more-social-proof-on-your-store-2', destination: '/', statusCode: 301 },
      { source: '/contact-partner', destination: '/contact-us', statusCode: 301 },
      { source: '/custom-form-formbuilder', destination: '/', statusCode: 301 },
      { source: '/customer-insights-dashboard', destination: '/customer-management', statusCode: 301 },
      { source: '/customer-journey-tracking', destination: '/customer-management', statusCode: 301 },
      { source: '/customer-retention-management', destination: '/customer-management', statusCode: 301 },
      { source: '/customer-success-manager', destination: '/', statusCode: 301 },
      { source: '/custon-form-formbuilder', destination: '/', statusCode: 301 },
      { source: '/delhi-meetup', destination: '/', statusCode: 301 },
      { source: '/ecomspark-2025', destination: '/', statusCode: 301 },
      { source: '/email-marketing-automation/shopify-email-vs-whatsapp-marketing', destination: '/', statusCode: 301 },
      { source: '/full-stack-developer', destination: '/', statusCode: 301 },
      { source: '/gallery', destination: '/', statusCode: 301 },
      { source: '/get-artificial-intelligence-and-upshot-your-abandoned-cart-recovery-performances', destination: '/', statusCode: 301 },
      { source: '/home', destination: '/', statusCode: 301 },
      { source: '/loyalty-rewards', destination: '/', statusCode: 301 },
      { source: '/meeting-request', destination: '/book-a-demo', statusCode: 301 },
      { source: '/meeting-request.', destination: '/book-a-demo', statusCode: 301 },
      { source: '/migration-from-klaviyo', destination: '/', statusCode: 301 },
      { source: '/pricing-2', destination: '/pricing', statusCode: 301 },
      { source: '/request-a-demo', destination: '/book-a-demo', statusCode: 301 },
      { source: '/rspv-uk-webinar', destination: '/', statusCode: 301 },
      { source: '/sales-pipeline-management', destination: '/sales-pipeline', statusCode: 301 },
      { source: '/schedule-a-call', destination: '/book-a-demo', statusCode: 301 },
      { source: '/shopify-unite-2021-online-store-2-0-and-themes-faqs', destination: '/', statusCode: 301 },
      { source: '/shopify-web-developer', destination: '/', statusCode: 301 },
      { source: '/sms-marketing', destination: '/multichannel-communication', statusCode: 301 },
      { source: '/technical-content-writer', destination: '/', statusCode: 301 },
      { source: '/videos/build-an-automated-push-message', destination: '/', statusCode: 301 },
      { source: '/whatsapp-chat', destination: '/whatsapp', statusCode: 301 },
      { source: '/whatsapp-marketing-tool-for-shopify', destination: '/whatsapp', statusCode: 301 },
      { source: '/work-smart-automate-your-marketing-today', destination: '/', statusCode: 301 },
    ];
  },
  images: {
    // What's New post images now come from the CMS (utils/whatsNewApi.js), rendered via
    // next/image in WhatsNewCard/WhatsNewDetail — unlike the blog's own components, which
    // deliberately use plain <img> for admin-uploaded media instead of allow-listing this host.
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'aiengagecrm-kb-portal.s3.ap-south-1.amazonaws.com',
      },
    ],
  },
};

export default nextConfig;
